### ISSUE TITLE
testify --coverage: it don't work

### ISSUE THREAD

**Issue by bukzor** [Yelp/Testify#310]
I have the distinct suspicion that nobody has used this code in years.

```
$ testify --coverage tests/auto_source_test.py
.........Traceback (most recent call last):
  File "/usr/bin/testify", line 25, in <module>
    test_program.main()
  File "/usr/lib/python2.6/dist-packages/testify/test_program.py", line 350, in main
    sys.exit(not TestProgram().run())
  File "/usr/lib/python2.6/dist-packages/testify/test_program.py", line 314, in run
    return runner.run()
  File "/usr/lib/python2.6/dist-packages/testify/test_runner.py", line 208, in run
    runnable()
  File "/usr/lib/python2.6/dist-packages/testify/plugins/code_coverage.py", line 21, in run_test_case
    code_coverage.start(test_case.__class__.__module__ + "." + test_case.__class__.__name__)
  File "/usr/lib/python2.6/dist-packages/testify/utils/code_coverage.py", line 42, in start
    assert not started
AssertionError
Coverage.py warning: Module old was never imported.
```

**Comment by asottile** [comment]
I thought I deleted this already O_o

**Comment by asottile** [comment]
Kill with fire

**Comment by bukzor** [comment]
I think you did, but I can't find the PR.

**Comment by asottile** [comment]
https://github.com/Yelp/Testify/pull/301
